### ISSUE TITLE
[PR]: PRD 17.26 : Erro ao associar grupo em um cliente

### ISSUE THREAD

**Issue by duarteamanda** [GabaCorreaSB/Password-Manager-Gaba-CLI#4]
### Informação de contato

robotfx@octaplus.com.br

### Descrição

Conforme mencionei no call, estamos com o erro na associação de um grupo, porém isso está ocorrendo em UAT e PRD.
![image007](https://user-images.githubusercontent.com/77294689/169910439-09a739ec-66e9-4401-aa15-b8c71bb5a25e.png)

### Produto

RobotFX

### Número da versão

0.17.29

### Qual ambiente o problema foi encontrado?

Produção

### Severidade

Não-Crítico

### Prioridade

Média

**Comment by GabaCorreaSB** [comment]
PR Aceita.

**Comment by GabaCorreaSB** [comment]
PR concluída.
Release 0.17.29

**Comment by GabaCorreaSB** [comment]
PR em progresso.
